/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/v0/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List MCP servers
         * @description Returns a list of all registered MCP servers
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Pagination cursor for retrieving next set of results.
                     *
                     *     Cursors are opaque strings returned in the `metadata.nextCursor` field of paginated responses. Always use the exact cursor value returned by the API.
                     */
                    cursor?: string;
                    /** @description Maximum number of items to return */
                    limit?: number;
                    /** @description Search servers by name (substring match) */
                    search?: string;
                    /** @description Filter servers updated since timestamp (RFC3339 datetime) */
                    updated_since?: string;
                    /** @description Filter by version ('latest' for latest version, or an exact version like '1.2.3') */
                    version?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of MCP servers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers/{serverName}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all versions of an MCP server
         * @description Returns all available versions for a specific MCP server, ordered by publication date (newest first)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-encoded server name (e.g., "com.example%2Fmy-server") */
                    serverName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of all versions for the server */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerList"];
                    };
                };
                /** @description Server not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Server not found */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers/{serverName}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific MCP server version
         * @description Returns detailed information about a specific version of an MCP server. Use the special version `latest` to get the latest version.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description URL-encoded server name (e.g., "com.example%2Fmy-server") */
                    serverName: string;
                    /** @description URL-encoded version to retrieve (e.g., "1.0.0" or "1.0.0%2B20130313144700" for versions with build metadata) */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed server information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"];
                    };
                };
                /** @description Server or version not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Server not found */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish MCP server (Optional)
         * @description Publish a new MCP server to the registry or update an existing one.
         *
         *     **Note**: This endpoint is optional for registry implementations. Read-only registries may not provide this functionality.
         *
         *     Authentication mechanism is registry-specific and may vary between implementations.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServerDetail"];
                };
            };
            responses: {
                /** @description Successfully published server */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"];
                    };
                };
                /** @description Unauthorized - Invalid or missing authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid or expired Registry JWT token */
                            error?: string;
                        };
                    };
                };
                /** @description Forbidden - Insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example You do not have permission to publish this server */
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Failed to publish server */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** @description Repository metadata for the MCP server source code. Enables users and security experts to inspect the code, improving transparency. */
        Repository: {
            /**
             * Format: uri
             * @description Repository URL for browsing source code. Should support both web browsing and git clone operations.
             * @example https://github.com/modelcontextprotocol/servers
             */
            url: string;
            /**
             * @description Repository hosting service identifier. Used by registries to determine validation and API access methods.
             * @example github
             */
            source: string;
            /**
             * @description Repository identifier from the hosting service (e.g., GitHub repo ID). Owned and determined by the source forge. Should remain stable across repository renames and may be used to detect repository resurrection attacks - if a repository is deleted and recreated, the ID should change. For GitHub, use: gh api repos/<owner>/<repo> --jq '.id'
             * @example b94b5f7e-c7c6-d760-2c78-a5e9b8a5b8c9
             */
            id?: string;
            /**
             * @description Optional relative path from repository root to the server location within a monorepo or nested package structure. Must be a clean relative path.
             * @example src/everything
             */
            subfolder?: string;
        };
        ServerList: {
            servers: components["schemas"]["ServerResponse"][];
            metadata?: {
                /**
                 * @description Pagination cursor for retrieving the next page of results.
                 *     Use this exact value in the `cursor` query parameter of your next request. If null or empty, there are no more results.
                 */
                nextCursor?: string;
                /**
                 * @description Number of items in current page
                 * @example 30
                 */
                count?: number;
            };
        };
        Package: {
            /**
             * @description Registry type indicating how to download packages (e.g., 'npm', 'pypi', 'oci', 'nuget', 'mcpb')
             * @example npm
             * @example pypi
             * @example oci
             * @example nuget
             * @example mcpb
             */
            registryType: string;
            /**
             * Format: uri
             * @description Base URL of the package registry
             * @example https://registry.npmjs.org
             * @example https://pypi.org
             * @example https://docker.io
             * @example https://api.nuget.org
             * @example https://github.com
             * @example https://gitlab.com
             */
            registryBaseUrl?: string;
            /**
             * @description Package identifier - either a package name (for registries) or URL (for direct downloads)
             * @example @modelcontextprotocol/server-brave-search
             * @example https://github.com/example/releases/download/v1.0.0/package.mcpb
             */
            identifier: string;
            /**
             * @description Package version. Must be a specific version. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
             * @example 1.0.2
             */
            version?: string;
            /**
             * @description SHA-256 hash of the package file for integrity verification. Required for MCPB packages and optional for other package types. Authors are responsible for generating correct SHA-256 hashes when creating server.json. If present, MCP clients must validate the downloaded file matches the hash before running packages to ensure file integrity.
             * @example fe333e598595000ae021bd27117db32ec69af6987f507ba7a63c90638ff633ce
             */
            fileSha256?: string;
            /**
             * @description A hint to help clients determine the appropriate runtime for the package. This field should be provided when `runtimeArguments` are present.
             * @example npx
             * @example uvx
             * @example docker
             * @example dnx
             */
            runtimeHint?: string;
            /** @description Transport protocol configuration for the package */
            transport: components["schemas"]["StdioTransport"] | components["schemas"]["StreamableHttpTransport"] | components["schemas"]["SseTransport"];
            /** @description A list of arguments to be passed to the package's runtime command (such as docker or npx). The `runtimeHint` field should be provided when `runtimeArguments` are present. */
            runtimeArguments?: components["schemas"]["Argument"][];
            /** @description A list of arguments to be passed to the package's binary. */
            packageArguments?: components["schemas"]["Argument"][];
            /** @description A mapping of environment variables to be set when running the package. */
            environmentVariables?: components["schemas"]["KeyValueInput"][];
        };
        Input: {
            /** @description A description of the input, which clients can use to provide context to the user. */
            description?: string;
            /** @default false */
            isRequired: boolean;
            /**
             * @description Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
             *
             *     When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
             * @default string
             * @enum {string}
             */
            format: "string" | "number" | "boolean" | "filepath";
            /**
             * @description The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
             *
             *     Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
             */
            value?: string;
            /**
             * @description Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
             * @default false
             */
            isSecret: boolean;
            /** @description The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead. */
            default?: string;
            /** @description A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input. */
            placeholder?: string;
            /**
             * @description A list of possible values for the input. If provided, the user must select one of these values.
             * @example []
             */
            choices?: string[];
        };
        InputWithVariables: components["schemas"]["Input"] & {
            /** @description A map of variable names to their values. Keys in the input `value` that are wrapped in `{curly_braces}` will be replaced with the corresponding variable values. */
            variables?: {
                [key: string]: components["schemas"]["Input"];
            };
        };
        /** @description A positional input is a value inserted verbatim into the command line. */
        PositionalArgument: components["schemas"]["InputWithVariables"] & ({
            /**
             * @example positional
             * @enum {string}
             */
            type: "positional";
            /**
             * @description An identifier for the positional argument. It is not part of the command line. It may be used by client configuration as a label identifying the argument. It is also used to identify the value in transport URL variable substitution.
             * @example file_path
             */
            valueHint?: string;
            /**
             * @description Whether the argument can be repeated multiple times in the command line.
             * @default false
             */
            isRepeated: boolean;
        } | unknown | unknown);
        /** @description A command-line `--flag={value}`. */
        NamedArgument: components["schemas"]["InputWithVariables"] & {
            /**
             * @example named
             * @enum {string}
             */
            type: "named";
            /**
             * @description The flag name, including any leading dashes.
             * @example --port
             */
            name: string;
            /**
             * @description Whether the argument can be repeated multiple times.
             * @default false
             */
            isRepeated: boolean;
        };
        KeyValueInput: components["schemas"]["InputWithVariables"] & {
            /**
             * @description Name of the header or environment variable.
             * @example SOME_VARIABLE
             */
            name: string;
        };
        /** @description Warning: Arguments construct command-line parameters that may contain user-provided input. This creates potential command injection risks if clients execute commands in a shell environment. For example, a malicious argument value like ';rm -rf ~/Development' could execute dangerous commands. Clients should prefer non-shell execution methods (e.g., posix_spawn) when possible to eliminate injection risks entirely. Where not possible, clients should obtain consent from users or agents to run the resolved command before execution. */
        Argument: components["schemas"]["PositionalArgument"] | components["schemas"]["NamedArgument"];
        StdioTransport: {
            /**
             * @description Transport type
             * @example stdio
             * @enum {string}
             */
            type: "stdio";
        };
        StreamableHttpTransport: {
            /**
             * @description Transport type
             * @example streamable-http
             * @enum {string}
             */
            type: "streamable-http";
            /**
             * @description URL template for the streamable-http transport. Variables in {curly_braces} reference argument valueHints, argument names, or environment variable names. After variable substitution, this should produce a valid URI.
             * @example https://api.example.com/mcp
             */
            url: string;
            /** @description HTTP headers to include */
            headers?: components["schemas"]["KeyValueInput"][];
        };
        SseTransport: {
            /**
             * @description Transport type
             * @example sse
             * @enum {string}
             */
            type: "sse";
            /**
             * Format: uri
             * @description Server-Sent Events endpoint URL
             * @example https://mcp-fs.example.com/sse
             */
            url: string;
            /** @description HTTP headers to include */
            headers?: components["schemas"]["KeyValueInput"][];
        };
        /** @description An optionally-sized icon that can be displayed in a user interface. */
        Icon: {
            /**
             * Format: uri
             * @description A standard URI pointing to an icon resource. Must be an HTTPS URL. Consumers SHOULD take steps to ensure URLs serving icons are from the same domain as the server or a trusted domain. Consumers SHOULD take appropriate precautions when consuming SVGs as they can contain executable JavaScript.
             * @example https://example.com/icon.png
             */
            src: string;
            /**
             * @description Optional MIME type override if the source MIME type is missing or generic. Must be one of: image/png, image/jpeg, image/jpg, image/svg+xml, image/webp.
             * @example image/png
             * @enum {string}
             */
            mimeType?: "image/png" | "image/jpeg" | "image/jpg" | "image/svg+xml" | "image/webp";
            /**
             * @description Optional array of strings that specify sizes at which the icon can be used. Each string should be in WxH format (e.g., '48x48', '96x96') or 'any' for scalable formats like SVG. If not provided, the client should assume that the icon can be used at any size.
             * @example [
             *       "48x48",
             *       "96x96"
             *     ]
             * @example [
             *       "any"
             *     ]
             */
            sizes?: string[];
            /**
             * @description Optional specifier for the theme this icon is designed for. 'light' indicates the icon is designed to be used with a light background, and 'dark' indicates the icon is designed to be used with a dark background. If not provided, the client should assume the icon can be used with any theme.
             * @enum {string}
             */
            theme?: "light" | "dark";
        };
        /** @description Schema for a static representation of an MCP server. Used in various contexts related to discovery, installation, and configuration. */
        ServerDetail: {
            /**
             * @description Server name in reverse-DNS format. Must contain exactly one forward slash separating namespace from server name.
             * @example io.github.user/weather
             */
            name: string;
            /**
             * @description Clear human-readable explanation of server functionality. Should focus on capabilities, not implementation details.
             * @example MCP server providing weather data and forecasts via OpenWeatherMap API
             */
            description: string;
            /**
             * @description Optional human-readable title or display name for the MCP server. MCP subregistries or clients MAY choose to use this for display purposes.
             * @example Weather API
             */
            title?: string;
            /** @description Optional repository metadata for the MCP server source code. Recommended for transparency and security inspection. */
            repository?: components["schemas"]["Repository"];
            /**
             * @description Version string for this server. SHOULD follow semantic versioning (e.g., '1.0.2', '2.1.0-alpha'). Equivalent of Implementation.version in MCP specification. Non-semantic versions are allowed but may not sort predictably. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
             * @example 1.0.2
             */
            version: string;
            /**
             * Format: uri
             * @description Optional URL to the server's homepage, documentation, or project website. This provides a central link for users to learn more about the server. Particularly useful when the server has custom installation instructions or setup requirements.
             * @example https://modelcontextprotocol.io/examples
             */
            websiteUrl?: string;
            /** @description Optional set of sized icons that the client can display in a user interface. Clients that support rendering icons MUST support at least the following MIME types: image/png and image/jpeg (safe, universal compatibility). Clients SHOULD also support: image/svg+xml (scalable but requires security precautions) and image/webp (modern, efficient format). */
            icons?: components["schemas"]["Icon"][];
            /**
             * Format: uri
             * @description JSON Schema URI for this server.json format
             * @example https://static.modelcontextprotocol.io/schemas/2025-10-17/server.schema.json
             */
            $schema?: string;
            packages?: components["schemas"]["Package"][];
            remotes?: (components["schemas"]["StreamableHttpTransport"] | components["schemas"]["SseTransport"])[];
            /** @description Extension metadata using reverse DNS namespacing for vendor-specific data */
            _meta?: {
                /**
                 * @description Publisher-provided metadata for downstream registries
                 * @example {
                 *       "tool": "publisher-cli",
                 *       "version": "1.2.3",
                 *       "buildInfo": {
                 *         "commit": "abc123def456",
                 *         "timestamp": "2023-12-01T10:30:00Z",
                 *         "pipelineId": "build-789"
                 *       }
                 *     }
                 */
                "io.modelcontextprotocol.registry/publisher-provided"?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description API response format with separated server data and registry metadata */
        ServerResponse: {
            server: components["schemas"]["ServerDetail"];
            /** @description Registry-managed metadata */
            _meta: {
                /** @description Official MCP registry metadata */
                "io.modelcontextprotocol.registry/official"?: {
                    /**
                     * @description Server lifecycle status
                     * @example active
                     * @enum {string}
                     */
                    status?: "active" | "deprecated" | "deleted";
                    /**
                     * Format: date-time
                     * @description Timestamp when the server was first published to the registry
                     * @example 2023-12-01T10:30:00Z
                     */
                    publishedAt?: string;
                    /**
                     * Format: date-time
                     * @description Timestamp when the server entry was last updated
                     * @example 2023-12-01T11:00:00Z
                     */
                    updatedAt?: string;
                    /**
                     * @description Whether this is the latest version of the server
                     * @example true
                     */
                    isLatest?: boolean;
                };
            } & {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
